version: '3.7'
networks:
  tabunet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.2.0/24

services:
  adminer:
    image: adminer
    ports:
      - 10080:8080
    networks:
      tabunet:
        ipv4_address: 172.20.2.4
  postgres:
    image: postgres:11
    networks:
      tabunet:
        ipv4_address: 172.20.2.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  tabu:
    build: tabu
    ports:
      - 8080:80
    networks:
      tabunet:
        ipv4_address: 172.20.2.8
    depends_on:
      - postgres
